// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: agent.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PauseContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseContainerRequest) Reset() {
	*x = PauseContainerRequest{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseContainerRequest) ProtoMessage() {}

func (x *PauseContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseContainerRequest.ProtoReflect.Descriptor instead.
func (*PauseContainerRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *PauseContainerRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type PauseContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseContainerResponse) Reset() {
	*x = PauseContainerResponse{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseContainerResponse) ProtoMessage() {}

func (x *PauseContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseContainerResponse.ProtoReflect.Descriptor instead.
func (*PauseContainerResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *PauseContainerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ResumeContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeContainerRequest) Reset() {
	*x = ResumeContainerRequest{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeContainerRequest) ProtoMessage() {}

func (x *ResumeContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeContainerRequest.ProtoReflect.Descriptor instead.
func (*ResumeContainerRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ResumeContainerRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type ResumeContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeContainerResponse) Reset() {
	*x = ResumeContainerResponse{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeContainerResponse) ProtoMessage() {}

func (x *ResumeContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeContainerResponse.ProtoReflect.Descriptor instead.
func (*ResumeContainerResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ResumeContainerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type EnsureContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FunctionName  string                 `protobuf:"bytes,1,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Env           map[string]string      `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureContainerRequest) Reset() {
	*x = EnsureContainerRequest{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureContainerRequest) ProtoMessage() {}

func (x *EnsureContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureContainerRequest.ProtoReflect.Descriptor instead.
func (*EnsureContainerRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *EnsureContainerRequest) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *EnsureContainerRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *EnsureContainerRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type DestroyContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FunctionName  string                 `protobuf:"bytes,1,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	ContainerId   string                 `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyContainerRequest) Reset() {
	*x = DestroyContainerRequest{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyContainerRequest) ProtoMessage() {}

func (x *DestroyContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyContainerRequest.ProtoReflect.Descriptor instead.
func (*DestroyContainerRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *DestroyContainerRequest) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *DestroyContainerRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type DestroyContainerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyContainerResponse) Reset() {
	*x = DestroyContainerResponse{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyContainerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyContainerResponse) ProtoMessage() {}

func (x *DestroyContainerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyContainerResponse.ProtoReflect.Descriptor instead.
func (*DestroyContainerResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *DestroyContainerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type WorkerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerInfo) Reset() {
	*x = WorkerInfo{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerInfo) ProtoMessage() {}

func (x *WorkerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerInfo.ProtoReflect.Descriptor instead.
func (*WorkerInfo) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *WorkerInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkerInfo) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *WorkerInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type InvokeWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,7,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimeoutMs     int32                  `protobuf:"varint,6,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeWorkerRequest) Reset() {
	*x = InvokeWorkerRequest{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeWorkerRequest) ProtoMessage() {}

func (x *InvokeWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeWorkerRequest.ProtoReflect.Descriptor instead.
func (*InvokeWorkerRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *InvokeWorkerRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *InvokeWorkerRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *InvokeWorkerRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *InvokeWorkerRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *InvokeWorkerRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type InvokeWorkerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeWorkerResponse) Reset() {
	*x = InvokeWorkerResponse{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeWorkerResponse) ProtoMessage() {}

func (x *InvokeWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeWorkerResponse.ProtoReflect.Descriptor instead.
func (*InvokeWorkerResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *InvokeWorkerResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *InvokeWorkerResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *InvokeWorkerResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// Phase 3: message for ListContainers.
type ListContainersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContainersRequest) Reset() {
	*x = ListContainersRequest{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContainersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContainersRequest) ProtoMessage() {}

func (x *ListContainersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContainersRequest.ProtoReflect.Descriptor instead.
func (*ListContainersRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

type ListContainersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Containers    []*ContainerState      `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContainersResponse) Reset() {
	*x = ListContainersResponse{}
	mi := &file_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContainersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContainersResponse) ProtoMessage() {}

func (x *ListContainersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContainersResponse.ProtoReflect.Descriptor instead.
func (*ListContainersResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

func (x *ListContainersResponse) GetContainers() []*ContainerState {
	if x != nil {
		return x.Containers
	}
	return nil
}

type ContainerState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	FunctionName  string                 `protobuf:"bytes,2,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                              // "RUNNING", "PAUSED", "STOPPED", "UNKNOWN"
	LastUsedAt    int64                  `protobuf:"varint,4,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"` // Unix Timestamp (seconds)
	ContainerName string                 `protobuf:"bytes,5,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix Timestamp (seconds) - container creation time
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerState) Reset() {
	*x = ContainerState{}
	mi := &file_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerState) ProtoMessage() {}

func (x *ContainerState) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerState.ProtoReflect.Descriptor instead.
func (*ContainerState) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{12}
}

func (x *ContainerState) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ContainerState) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *ContainerState) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ContainerState) GetLastUsedAt() int64 {
	if x != nil {
		return x.LastUsedAt
	}
	return 0
}

func (x *ContainerState) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *ContainerState) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// Metrics API
type GetContainerMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContainerMetricsRequest) Reset() {
	*x = GetContainerMetricsRequest{}
	mi := &file_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContainerMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContainerMetricsRequest) ProtoMessage() {}

func (x *GetContainerMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContainerMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetContainerMetricsRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{13}
}

func (x *GetContainerMetricsRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type GetContainerMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       *ContainerMetrics      `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContainerMetricsResponse) Reset() {
	*x = GetContainerMetricsResponse{}
	mi := &file_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContainerMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContainerMetricsResponse) ProtoMessage() {}

func (x *GetContainerMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContainerMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetContainerMetricsResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{14}
}

func (x *GetContainerMetricsResponse) GetMetrics() *ContainerMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type ContainerMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	FunctionName  string                 `protobuf:"bytes,2,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	ContainerName string                 `protobuf:"bytes,3,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`                                       // "RUNNING", "PAUSED", "STOPPED", "UNKNOWN"
	MemoryCurrent uint64                 `protobuf:"varint,5,opt,name=memory_current,json=memoryCurrent,proto3" json:"memory_current,omitempty"` // bytes
	MemoryMax     uint64                 `protobuf:"varint,6,opt,name=memory_max,json=memoryMax,proto3" json:"memory_max,omitempty"`             // bytes
	OomEvents     uint64                 `protobuf:"varint,7,opt,name=oom_events,json=oomEvents,proto3" json:"oom_events,omitempty"`             // count
	CpuUsageNs    uint64                 `protobuf:"varint,8,opt,name=cpu_usage_ns,json=cpuUsageNs,proto3" json:"cpu_usage_ns,omitempty"`        // nanoseconds
	ExitCode      uint32                 `protobuf:"varint,9,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	RestartCount  uint32                 `protobuf:"varint,10,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`
	ExitTime      int64                  `protobuf:"varint,11,opt,name=exit_time,json=exitTime,proto3" json:"exit_time,omitempty"`          // Unix Timestamp (秒)
	CollectedAt   int64                  `protobuf:"varint,12,opt,name=collected_at,json=collectedAt,proto3" json:"collected_at,omitempty"` // Unix Timestamp (秒)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerMetrics) Reset() {
	*x = ContainerMetrics{}
	mi := &file_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerMetrics) ProtoMessage() {}

func (x *ContainerMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerMetrics.ProtoReflect.Descriptor instead.
func (*ContainerMetrics) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{15}
}

func (x *ContainerMetrics) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ContainerMetrics) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *ContainerMetrics) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *ContainerMetrics) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ContainerMetrics) GetMemoryCurrent() uint64 {
	if x != nil {
		return x.MemoryCurrent
	}
	return 0
}

func (x *ContainerMetrics) GetMemoryMax() uint64 {
	if x != nil {
		return x.MemoryMax
	}
	return 0
}

func (x *ContainerMetrics) GetOomEvents() uint64 {
	if x != nil {
		return x.OomEvents
	}
	return 0
}

func (x *ContainerMetrics) GetCpuUsageNs() uint64 {
	if x != nil {
		return x.CpuUsageNs
	}
	return 0
}

func (x *ContainerMetrics) GetExitCode() uint32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ContainerMetrics) GetRestartCount() uint32 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

func (x *ContainerMetrics) GetExitTime() int64 {
	if x != nil {
		return x.ExitTime
	}
	return 0
}

func (x *ContainerMetrics) GetCollectedAt() int64 {
	if x != nil {
		return x.CollectedAt
	}
	return 0
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\fesb.agent.v1\":\n" +
	"\x15PauseContainerRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\"2\n" +
	"\x16PauseContainerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\";\n" +
	"\x16ResumeContainerRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\"3\n" +
	"\x17ResumeContainerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xcc\x01\n" +
	"\x16EnsureContainerRequest\x12#\n" +
	"\rfunction_name\x18\x01 \x01(\tR\ffunctionName\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12?\n" +
	"\x03env\x18\x03 \x03(\v2-.esb.agent.v1.EnsureContainerRequest.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"a\n" +
	"\x17DestroyContainerRequest\x12#\n" +
	"\rfunction_name\x18\x01 \x01(\tR\ffunctionName\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\"4\n" +
	"\x18DestroyContainerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"c\n" +
	"\n" +
	"WorkerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\"\xa9\x02\n" +
	"\x13InvokeWorkerRequest\x12!\n" +
	"\fcontainer_id\x18\a \x01(\tR\vcontainerId\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12H\n" +
	"\aheaders\x18\x05 \x03(\v2..esb.agent.v1.InvokeWorkerRequest.HeadersEntryR\aheaders\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x06 \x01(\x05R\ttimeoutMs\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x01\x10\x02J\x04\b\x02\x10\x03R\n" +
	"ip_addressR\x04port\"\xd2\x01\n" +
	"\x14InvokeWorkerResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12I\n" +
	"\aheaders\x18\x02 \x03(\v2/.esb.agent.v1.InvokeWorkerResponse.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x17\n" +
	"\x15ListContainersRequest\"V\n" +
	"\x16ListContainersResponse\x12<\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2\x1c.esb.agent.v1.ContainerStateR\n" +
	"containers\"\xd8\x01\n" +
	"\x0eContainerState\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12#\n" +
	"\rfunction_name\x18\x02 \x01(\tR\ffunctionName\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12 \n" +
	"\flast_used_at\x18\x04 \x01(\x03R\n" +
	"lastUsedAt\x12%\n" +
	"\x0econtainer_name\x18\x05 \x01(\tR\rcontainerName\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\"?\n" +
	"\x1aGetContainerMetricsRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\"W\n" +
	"\x1bGetContainerMetricsResponse\x128\n" +
	"\ametrics\x18\x01 \x01(\v2\x1e.esb.agent.v1.ContainerMetricsR\ametrics\"\xa0\x03\n" +
	"\x10ContainerMetrics\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12#\n" +
	"\rfunction_name\x18\x02 \x01(\tR\ffunctionName\x12%\n" +
	"\x0econtainer_name\x18\x03 \x01(\tR\rcontainerName\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12%\n" +
	"\x0ememory_current\x18\x05 \x01(\x04R\rmemoryCurrent\x12\x1d\n" +
	"\n" +
	"memory_max\x18\x06 \x01(\x04R\tmemoryMax\x12\x1d\n" +
	"\n" +
	"oom_events\x18\a \x01(\x04R\toomEvents\x12 \n" +
	"\fcpu_usage_ns\x18\b \x01(\x04R\n" +
	"cpuUsageNs\x12\x1b\n" +
	"\texit_code\x18\t \x01(\rR\bexitCode\x12#\n" +
	"\rrestart_count\x18\n" +
	" \x01(\rR\frestartCount\x12\x1b\n" +
	"\texit_time\x18\v \x01(\x03R\bexitTime\x12!\n" +
	"\fcollected_at\x18\f \x01(\x03R\vcollectedAt2\xa1\x05\n" +
	"\fAgentService\x12Q\n" +
	"\x0fEnsureContainer\x12$.esb.agent.v1.EnsureContainerRequest\x1a\x18.esb.agent.v1.WorkerInfo\x12a\n" +
	"\x10DestroyContainer\x12%.esb.agent.v1.DestroyContainerRequest\x1a&.esb.agent.v1.DestroyContainerResponse\x12[\n" +
	"\x0ePauseContainer\x12#.esb.agent.v1.PauseContainerRequest\x1a$.esb.agent.v1.PauseContainerResponse\x12^\n" +
	"\x0fResumeContainer\x12$.esb.agent.v1.ResumeContainerRequest\x1a%.esb.agent.v1.ResumeContainerResponse\x12[\n" +
	"\x0eListContainers\x12#.esb.agent.v1.ListContainersRequest\x1a$.esb.agent.v1.ListContainersResponse\x12j\n" +
	"\x13GetContainerMetrics\x12(.esb.agent.v1.GetContainerMetricsRequest\x1a).esb.agent.v1.GetContainerMetricsResponse\x12U\n" +
	"\fInvokeWorker\x12!.esb.agent.v1.InvokeWorkerRequest\x1a\".esb.agent.v1.InvokeWorkerResponseBAZ?github.com/poruru/edge-serverless-box/services/agent/pkg/api/v1b\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var (
	file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
	file_agent_proto_goTypes  = []any{
		(*PauseContainerRequest)(nil),       // 0: esb.agent.v1.PauseContainerRequest
		(*PauseContainerResponse)(nil),      // 1: esb.agent.v1.PauseContainerResponse
		(*ResumeContainerRequest)(nil),      // 2: esb.agent.v1.ResumeContainerRequest
		(*ResumeContainerResponse)(nil),     // 3: esb.agent.v1.ResumeContainerResponse
		(*EnsureContainerRequest)(nil),      // 4: esb.agent.v1.EnsureContainerRequest
		(*DestroyContainerRequest)(nil),     // 5: esb.agent.v1.DestroyContainerRequest
		(*DestroyContainerResponse)(nil),    // 6: esb.agent.v1.DestroyContainerResponse
		(*WorkerInfo)(nil),                  // 7: esb.agent.v1.WorkerInfo
		(*InvokeWorkerRequest)(nil),         // 8: esb.agent.v1.InvokeWorkerRequest
		(*InvokeWorkerResponse)(nil),        // 9: esb.agent.v1.InvokeWorkerResponse
		(*ListContainersRequest)(nil),       // 10: esb.agent.v1.ListContainersRequest
		(*ListContainersResponse)(nil),      // 11: esb.agent.v1.ListContainersResponse
		(*ContainerState)(nil),              // 12: esb.agent.v1.ContainerState
		(*GetContainerMetricsRequest)(nil),  // 13: esb.agent.v1.GetContainerMetricsRequest
		(*GetContainerMetricsResponse)(nil), // 14: esb.agent.v1.GetContainerMetricsResponse
		(*ContainerMetrics)(nil),            // 15: esb.agent.v1.ContainerMetrics
		nil,                                 // 16: esb.agent.v1.EnsureContainerRequest.EnvEntry
		nil,                                 // 17: esb.agent.v1.InvokeWorkerRequest.HeadersEntry
		nil,                                 // 18: esb.agent.v1.InvokeWorkerResponse.HeadersEntry
	}
)
var file_agent_proto_depIdxs = []int32{
	16, // 0: esb.agent.v1.EnsureContainerRequest.env:type_name -> esb.agent.v1.EnsureContainerRequest.EnvEntry
	17, // 1: esb.agent.v1.InvokeWorkerRequest.headers:type_name -> esb.agent.v1.InvokeWorkerRequest.HeadersEntry
	18, // 2: esb.agent.v1.InvokeWorkerResponse.headers:type_name -> esb.agent.v1.InvokeWorkerResponse.HeadersEntry
	12, // 3: esb.agent.v1.ListContainersResponse.containers:type_name -> esb.agent.v1.ContainerState
	15, // 4: esb.agent.v1.GetContainerMetricsResponse.metrics:type_name -> esb.agent.v1.ContainerMetrics
	4,  // 5: esb.agent.v1.AgentService.EnsureContainer:input_type -> esb.agent.v1.EnsureContainerRequest
	5,  // 6: esb.agent.v1.AgentService.DestroyContainer:input_type -> esb.agent.v1.DestroyContainerRequest
	0,  // 7: esb.agent.v1.AgentService.PauseContainer:input_type -> esb.agent.v1.PauseContainerRequest
	2,  // 8: esb.agent.v1.AgentService.ResumeContainer:input_type -> esb.agent.v1.ResumeContainerRequest
	10, // 9: esb.agent.v1.AgentService.ListContainers:input_type -> esb.agent.v1.ListContainersRequest
	13, // 10: esb.agent.v1.AgentService.GetContainerMetrics:input_type -> esb.agent.v1.GetContainerMetricsRequest
	8,  // 11: esb.agent.v1.AgentService.InvokeWorker:input_type -> esb.agent.v1.InvokeWorkerRequest
	7,  // 12: esb.agent.v1.AgentService.EnsureContainer:output_type -> esb.agent.v1.WorkerInfo
	6,  // 13: esb.agent.v1.AgentService.DestroyContainer:output_type -> esb.agent.v1.DestroyContainerResponse
	1,  // 14: esb.agent.v1.AgentService.PauseContainer:output_type -> esb.agent.v1.PauseContainerResponse
	3,  // 15: esb.agent.v1.AgentService.ResumeContainer:output_type -> esb.agent.v1.ResumeContainerResponse
	11, // 16: esb.agent.v1.AgentService.ListContainers:output_type -> esb.agent.v1.ListContainersResponse
	14, // 17: esb.agent.v1.AgentService.GetContainerMetrics:output_type -> esb.agent.v1.GetContainerMetricsResponse
	9,  // 18: esb.agent.v1.AgentService.InvokeWorker:output_type -> esb.agent.v1.InvokeWorkerResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
