// Auto-generated by branding generator. Do not edit directly.
// Source: tools/branding/templates/docker-bake.hcl.tmpl

// Base/control images (targets are configured at runtime via bake overrides).
variable "REGISTRY" {
  default = ""
}

variable "HOME" {
  default = ""
}

variable "BRAND_SLUG" {
  default = "esb"
}

variable "BRAND_HOME" {
  default = ".${BRAND_SLUG}"
}

variable "CERT_DIR" {
  default = "./${BRAND_HOME}/certs"
}

target "lambda-base" {
  context    = "."
  dockerfile = "runtime-hooks/python/docker/Dockerfile"
  tags       = ["${REGISTRY}esb-lambda-base:latest"]
  output     = ["type=image,push=true"]
}

target "os-base" {
  context    = "services/common"
  dockerfile = "Dockerfile.os-base"
  tags = ["${REGISTRY}esb-os-base:latest"]
  args = {
    ROOT_CA_MOUNT_ID = "root_ca"
  }
  output = ["type=image,push=true"]
  secret = ["id=root_ca,src=${CERT_DIR}/rootCA.crt"]
}

target "python-base" {
  context    = "services/common"
  dockerfile = "Dockerfile.python-base"
  tags = ["${REGISTRY}esb-python-base:latest"]
  args = {
    ROOT_CA_MOUNT_ID = "root_ca"
  }
  output = ["type=image,push=true"]
  secret = ["id=root_ca,src=${CERT_DIR}/rootCA.crt"]
}

group "base-images" {
  targets = ["lambda-base", "os-base", "python-base"]
}

// Control plane images (Docker mode).
target "gateway-docker" {
  context    = "services/gateway"
  dockerfile = "Dockerfile.docker"
  contexts = {
    config      = "services/gateway/config"
    common      = "services/common"
    python-base = "target:python-base"
  }
  args = {
    PYTHON_BASE_IMAGE = "python-base"
    SERVICE_USER      = "esb"
    SERVICE_UID       = "1000"
    SERVICE_GID       = "1000"
  }
  tags   = ["${REGISTRY}esb-gateway-docker:latest"]
  output = ["type=image,push=true"]
}

target "agent-docker" {
  context    = "services/agent"
  dockerfile = "Dockerfile.docker"
  contexts = {
    os-base = "target:os-base"
  }
  args = {
    OS_BASE_IMAGE = "os-base"
  }
  tags   = ["${REGISTRY}esb-agent-docker:latest"]
  output = ["type=image,push=true"]
}

// Control plane images (shared/provisioner).
target "provisioner" {
  context    = "services/provisioner"
  dockerfile = "Dockerfile"
  contexts = {
    config           = "services/gateway/config"
    generator_assets = "runtime-hooks/python/sitecustomize/site-packages"
    python-base      = "target:python-base"
  }
  args = {
    PYTHON_BASE_IMAGE = "python-base"
  }
  tags   = ["${REGISTRY}esb-provisioner:latest"]
  output = ["type=image,push=true"]
}

// Control plane images (containerd mode).
target "runtime-node-containerd" {
  context    = "services/runtime-node"
  dockerfile = "Dockerfile.containerd"
  contexts = {
    os-base = "target:os-base"
  }
  args = {
    OS_BASE_IMAGE = "os-base"
  }
  tags   = ["${REGISTRY}esb-runtime-node-containerd:latest"]
  output = ["type=image,push=true"]
}

target "agent-containerd" {
  context    = "services/agent"
  dockerfile = "Dockerfile.containerd"
  contexts = {
    os-base = "target:os-base"
  }
  args = {
    OS_BASE_IMAGE = "os-base"
  }
  tags   = ["${REGISTRY}esb-agent-containerd:latest"]
  output = ["type=image,push=true"]
}

target "gateway-containerd" {
  context    = "services/gateway"
  dockerfile = "Dockerfile.containerd"
  contexts = {
    config      = "services/gateway/config"
    common      = "services/common"
    python-base = "target:python-base"
  }
  args = {
    PYTHON_BASE_IMAGE = "python-base"
    SERVICE_USER      = "esb"
    SERVICE_UID       = "1000"
    SERVICE_GID       = "1000"
  }
  tags   = ["${REGISTRY}esb-gateway-containerd:latest"]
  output = ["type=image,push=true"]
}

group "control-images-docker" {
  targets = ["gateway-docker", "agent-docker", "provisioner"]
}

group "control-images-containerd" {
  targets = ["runtime-node-containerd", "gateway-containerd", "agent-containerd", "provisioner"]
}

group "default" {
  targets = ["base-images", "control-images-docker", "control-images-containerd"]
}
