"""Centralized constants for the E2E runner to eliminate magic strings."""

# Environment Variable Keys
ENV_ENV = "ENV"
ENV_MODE = "MODE"
ENV_PROJECT_NAME = "PROJECT_NAME"
ENV_IMAGE_TAG = "IMAGE_TAG"
ENV_IMAGE_PREFIX = "IMAGE_PREFIX"
ENV_CONTAINER_REGISTRY = "CONTAINER_REGISTRY"
ENV_CONFIG_DIR = "CONFIG_DIR"
ENV_NETWORK_EXTERNAL = "NETWORK_EXTERNAL"
ENV_LAMBDA_NETWORK = "LAMBDA_NETWORK"
ENV_SUBNET_EXTERNAL = "SUBNET_EXTERNAL"
ENV_RUNTIME_NET_SUBNET = "RUNTIME_NET_SUBNET"
ENV_RUNTIME_NODE_IP = "RUNTIME_NODE_IP"
ENV_ROOT_CA_MOUNT_ID = "ROOT_CA_MOUNT_ID"

# Auth & Security
ENV_AUTH_USER = "AUTH_USER"
ENV_AUTH_PASS = "AUTH_PASS"
ENV_JWT_SECRET_KEY = "JWT_SECRET_KEY"
ENV_X_API_KEY = "X_API_KEY"
ENV_RUSTFS_ACCESS_KEY = "RUSTFS_ACCESS_KEY"
ENV_RUSTFS_SECRET_KEY = "RUSTFS_SECRET_KEY"

# Generator/Sync Constants
ENV_GATEWAY_FUNCTIONS_YML = "GATEWAY_FUNCTIONS_YML"
ENV_GATEWAY_ROUTING_YML = "GATEWAY_ROUTING_YML"

# Proxy & Misc
ENV_DOCKER_BUILDKIT = "DOCKER_BUILDKIT"
ENV_CLI_CMD = "CLI_CMD"
ENV_CLI_SRC_ROOT = "CLI_SRC_ROOT"

# Gateway & TLS
ENV_AUTH_ENDPOINT_PATH = "AUTH_ENDPOINT_PATH"
ENV_VERIFY_SSL = "VERIFY_SSL"
ENV_CONTAINERS_NETWORK = "CONTAINERS_NETWORK"
ENV_GATEWAY_INTERNAL_URL = "GATEWAY_INTERNAL_URL"
ENV_AGENT_GRPC_TLS_ENABLED = "AGENT_GRPC_TLS_ENABLED"
ENV_AGENT_GRPC_TLS_CA_CERT_PATH = "AGENT_GRPC_TLS_CA_CERT_PATH"
ENV_AGENT_GRPC_TLS_CERT_PATH = "AGENT_GRPC_TLS_CERT_PATH"
ENV_AGENT_GRPC_TLS_KEY_PATH = "AGENT_GRPC_TLS_KEY_PATH"
ENV_ROOT_CA_FINGERPRINT = "ROOT_CA_FINGERPRINT"
ENV_ROOT_CA_CERT_FILENAME = "ROOT_CA_CERT_FILENAME"
ENV_CERT_DIR = "CERT_DIR"  # While used as a key in env, also used as default fallback

PORT_GATEWAY_HTTPS = "PORT_GATEWAY_HTTPS"
PORT_GATEWAY_HTTP = "PORT_GATEWAY_HTTP"
PORT_VICTORIALOGS = "PORT_VICTORIALOGS"
PORT_DATABASE = "PORT_DATABASE"
PORT_S3 = "PORT_S3"
PORT_S3_MGMT = "PORT_S3_MGMT"
PORT_REGISTRY = "PORT_REGISTRY"
PORT_AGENT_GRPC = "PORT_AGENT_GRPC"
PORT_AGENT_METRICS = "PORT_AGENT_METRICS"

# Legacy Mapping Keys (process-level)
ENV_GatewayPort = "GATEWAY_PORT"
ENV_GatewayURL = "GATEWAY_URL"
ENV_VictoriaLogsPort = "VICTORIALOGS_PORT"
ENV_VictoriaLogsURL = "VICTORIALOGS_URL"
ENV_AgentGrpcAddress = "AGENT_GRPC_ADDRESS"

# Default Values
DEFAULT_AGENT_REGISTRY = "registry:5010"
DEFAULT_ROOT_CA_FILENAME = "rootCA.crt"
DEFAULT_AUTH_Path = "/user/auth/v1"
