package meta

// Auto-generated by branding generator. Do not edit directly.
// Source: tools/branding/templates/meta/meta.go.tmpl
// Where: meta/meta.go
// What: Core project metadata and constants.
// Why: Centralize project identity and configuration constants.

const (
    // Project Identity
    AppName     = "esb"
    Slug        = "esb"
    EnvPrefix   = "ESB"
    EnvVarEnv   = "ENV"
    ImagePrefix = "esb"
    LabelPrefix = "com.esb"

    // Directory Layout
    HomeDir    = ".esb"
    OutputDir  = ".esb"
    StagingDir = ".staging"

    // Certificate Constants
    RootCAMountID      = "esb_root_ca"
    RootCACertFilename = "rootCA.crt"
    RootCACertPath     = "/usr/local/share/ca-certificates/rootCA.crt"

    // Runtime / CNI Constants
    RuntimeContainerPrefix     = Slug
    RuntimeNamespace           = Slug
    RuntimeCNIName             = Slug + "-net"
    RuntimeCNIBridge           = Slug + "0"
    RuntimeCNIDir              = "/run/" + Slug + "/cni"
    RuntimeResolvConfPath      = "/run/containerd/" + Slug + "/resolv.conf"
    RuntimeLabelEnv            = Slug + "_env"
    RuntimeLabelFunction       = Slug + "_function"
    RuntimeLabelCreatedBy      = "created_by"
    RuntimeLabelCreatedByValue = Slug + "-agent"
)
