// Code generated by tools/branding/generate.py; DO NOT EDIT.
// Where: services/agent/internal/runtime/branding_gen.go
// What: Branding constants for runtime naming and paths.
// Why: Keep runtime identifiers derived from the configured brand.
package runtime

const (
	BrandingSlug                       = "esb"
	BrandingEnvVarEnv                  = "ESB_ENV"
	BrandingRuntimeContainerPrefix     = "esb"
	BrandingRuntimeNamespace           = "esb"
	BrandingRuntimeCNIName             = "esb-net"
	BrandingRuntimeCNIBridge           = "esb0"
	BrandingRuntimeCNIDir              = "/run/esb/cni"
	BrandingRuntimeResolvConfPath      = "/run/containerd/esb/resolv.conf"
	BrandingRuntimeLabelEnv            = "esb_env"
	BrandingRuntimeLabelFunction       = "esb_function"
	BrandingRuntimeLabelCreatedBy      = "created_by"
	BrandingRuntimeLabelCreatedByValue = "esb-agent"
	BrandingRootCACertPath             = "/usr/local/share/ca-certificates/rootCA.crt"
)
