#!/bin/sh
# Auto-generated by branding generator. Do not edit directly.
# Source: tools/branding/templates/services/runtime-node/entrypoint.sh.tmpl
# Where: services/runtime-node/entrypoint.sh
# What: Dispatch runtime-node entrypoints by mode.
# Why: Keep mode-specific setup isolated while retaining default behavior.
set -eu

mode="${ESB_RUNTIME_MODE:-${ESB_RUNTIME_ENTRYPOINT:-containerd}}"

case "$mode" in
  firecracker|fc)
    exec /entrypoint.firecracker.sh "$@"
    ;;
  containerd|"")
    exec /entrypoint.containerd.sh "$@"
    ;;
  *)
    echo "ERROR: Unknown ESB_RUNTIME_MODE=$mode" >&2
    exit 1
    ;;
esac
